# Generated by Django 4.2.3 on 2023-12-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailview', '0002_alter_email_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='your_mail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(null=True, related_name='receive_mail', to=settings.AUTH_USER_MODEL),
        ),
    ]
