# Generated by Django 4.2.3 on 2023-12-18 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailview', '0004_alter_email_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='receive_mail', to=settings.AUTH_USER_MODEL),
        ),
    ]
